"""add pre-masked PII columns and composite created_at index

Revision ID: 88fec555d28c
Revises: d42ff286429c
Create Date: 2026-06-20 18:22:58.502044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fec555d28c'
down_revision: Union[str, None] = 'd42ff286429c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aadhaar_masked', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('pan_masked', sa.String(length=20), nullable=True))
    op.create_index('ix_users_is_deleted_created_at', 'users', ['is_deleted', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_is_deleted_created_at', table_name='users')
    op.drop_column('users', 'pan_masked')
    op.drop_column('users', 'aadhaar_masked')
    # ### end Alembic commands ###
