"""add place_of_birth and date_of_birth indexes

Revision ID: fa62c018c300
Revises: 88fec555d28c
Create Date: 2026-06-20 23:26:38.677195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa62c018c300'
down_revision: Union[str, None] = '88fec555d28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_date_of_birth', 'users', ['date_of_birth'], unique=False)
    op.create_index('ix_users_place_of_birth', 'users', ['place_of_birth'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_place_of_birth', table_name='users')
    op.drop_index('ix_users_date_of_birth', table_name='users')
    # ### end Alembic commands ###
